// This file was autogenerated by D:\my projects\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/billboard/billboard.js', ['my.Billboard'], ['og.Billboard', 'og.EntityCollection', 'og.inheritance', 'og.math.Vector2', 'og.math.Vector3', 'og.node.RenderNode']);
