// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/billboard/billboard.js', ['my.Billboard'], ['og.Billboard', 'og.Entity', 'og.EntityCollection', 'og.GeoImage', 'og.Label', 'og.inheritance', 'og.math.Vector2', 'og.math.Vector3', 'og.node.RenderNode'], false);
