// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/polyline/myPolyline.js', ['my.Polyline'], ['og.Entity', 'og.EntityCollection', 'og.Label', 'og.Polyline', 'og.inheritance', 'og.scene.RenderNode'], false);
