language: node_js
os: linux
node_js:
- node
script:
- npm test
branches:  
  on:
  - /^v\d+(\.\d+)+$/ # expected format: v1.0.0
  - master
before_deploy:
- npm run build
- cd dist/@openglobus
- zip ${TRAVIS_TAG}-dist.zip *
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: ${TRAVIS_TAG}-dist.zip
  skip_cleanup: true
  on:
    tags: true