// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/earth/htmlPoint.js', ['HtmlPoint'], ['og.LonLat'], false);
goog.addDependency('../../../og/sandbox/earth/htmlPointCollection.js', ['HtmlPointCollection'], ['og.inheritance'], false);
