// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/earth/earth.js', ['Earth'], ['og.Entity', 'og.EntityCollection', 'og.LineString', 'og.inheritance', 'og.node.RenderNode', 'og.shape.Sphere'], false);
