// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/earth/earthNavigation.js', ['EarthNavigation'], ['og.bv.Sphere', 'og.control.Control', 'og.inheritance', 'og.math', 'og.math.Matrix4', 'og.math.Quaternion', 'og.math.Ray', 'og.math.Vector3'], false);
goog.addDependency('../../../og/sandbox/earth/htmlPoint.js', ['HtmlPoint'], ['og.LonLat'], false);
goog.addDependency('../../../og/sandbox/earth/htmlPointCollection.js', ['HtmlPointCollection'], ['og.inheritance'], false);
