// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/triangle/triangle.js', ['my.Triangle'], ['og.Extent', 'og.LonLat', 'og.PlanetSegmentHelper', 'og.math', 'og.scene.RenderNode', 'og.webgl.Framebuffer'], false);
