// This file was autogenerated by D:\my projects\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/label/label.js', ['my.Label'], ['og.inheritance', 'og.node.RenderNode', 'og.shaderProgram.sphericalBillboard']);
