// This file was autogenerated by D:\my projects\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/geoImage/geoImage.js', ['GeoImage'], ['og.Extent', 'og.LonLat', 'og.inheritance', 'og.node.RenderNode']);
