// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/linering3d/myLineRing.js', ['my.LineRing'], ['og.Entity', 'og.EntityCollection', 'og.Extent', 'og.Label', 'og.LonLat', 'og.inheritance', 'og.scene.RenderNode'], false);
