// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/linestring2/myLineString2.js', ['my.LineString2'], ['og.inheritance', 'og.math.Vector2', 'og.math.Vector3', 'og.node.RenderNode'], false);
