// This file was autogenerated by D:\my projects\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/heatmap/heatmap.js', ['my.Heatmap'], ['og.node.RenderNode']);
