// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/linestring/myLineString.js', ['my.LineString'], ['og.Entity', 'og.EntityCollection', 'og.Label', 'og.LineString', 'og.inheritance', 'og.scene.RenderNode'], false);
