// This file was autogenerated by D:\my projects\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/sphere/my_sphere.js', ['my.Sphere'], ['og.math', 'og.math.Matrix4', 'og.math.Vector3', 'og.node.RenderNode', 'og.shapes.Sphere']);
