// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/sphere/my_sphere.js', ['my.Sphere'], ['og.light.PointLight', 'og.math', 'og.math.Matrix4', 'og.math.Vector3', 'og.node.RenderNode', 'og.shaderProgram.sphere', 'og.shape.Sphere'], false);
goog.addDependency('../../../og/sandbox/sphere/sphere.js', ['og.shaderProgram.sphere'], ['og.shaderProgram', 'og.shaderProgram.ShaderProgram', 'og.shaderProgram.types', 'og.utils'], false);
