runs:
  using: "composite"
  steps:

    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'
        cache-dependency-path: package-lock.json
        registry-url: https://registry.npmjs.org/
        scope: '@openglobus'

    - name: Install dependencies
      shell: bash
      run: npm ci --prefer-offline --no-audit
