// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/atmosphere/atmosphere.js', ['Atmosphere'], ['og.light.PointLight', 'og.math', 'og.math.Matrix4', 'og.math.Vector3', 'og.node.RenderNode', 'og.shaderProgram.atmosphereSpace', 'og.shaderProgram.sphere', 'og.shape.Sphere'], false);
goog.addDependency('../../../og/sandbox/atmosphere/atmosphereFromSpace.js', ['og.shaderProgram.atmosphereSpace'], ['og.shaderProgram', 'og.shaderProgram.ShaderProgram', 'og.shaderProgram.types', 'og.utils'], false);
goog.addDependency('../../../og/sandbox/atmosphere/sphere.js', ['og.shaderProgram.sphere'], ['og.shaderProgram', 'og.shaderProgram.ShaderProgram', 'og.shaderProgram.types', 'og.utils'], false);
