// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/mbuff/mbuff.js', ['MBuff'], ['og.math', 'og.scene.RenderNode', 'og.webgl.MultiFramebuffer'], false);
