// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/pointcloud/myPointCloud.js', ['my.PointCloud'], ['og.Entity', 'og.EntityCollection', 'og.Label', 'og.LineString', 'og.inheritance', 'og.scene.RenderNode'], false);
