// This file was autogenerated by D:\my projects\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/2/mycubes.js', ['my.Cubes'], ['og.class', 'og.math', 'og.math.Matrix4', 'og.math.Quaternion', 'og.math.Vector3', 'og.node.RenderNode']);
