// This file was autogenerated by D:\my projects\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/2/mycube.js', ['my.Cube'], ['og._class_', 'og.math', 'og.math.Matrix4', 'og.math.Quaternion', 'og.math.Vector3', 'og.node.Node3D', 'og.shaderProgram', 'og.shaderProgram.ShaderProgram', 'og.shaderProgram.types']);
