export const DEFAULT_PROJECTOR_TEXTURE_UNIT_START = 6;
export const DEFAULT_SHADOW_TEXTURE_UNIT_START = 10;
export const DEFAULT_CASCADE_SHADOW_TEXTURE_UNIT_START = 14;

export const TERRAIN_PROJECTOR_TEXTURE_UNIT_OFFSET = 6;
export const TERRAIN_SHADOW_TEXTURE_UNIT_OFFSET = 10;
export const TERRAIN_CASCADE_SHADOW_TEXTURE_UNIT_OFFSET = 11;
