// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../og/sandbox/linering/myLineRing.js', ['my.LineRing'], ['og.Entity', 'og.EntityCollection', 'og.Label', 'og.inheritance', 'og.scene.RenderNode'], false);
